version: "3"
services:
  basic-postgres:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./tmp:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - network
networks:
  network:
    driver: bridge